### ISSUE TITLE
109.1 error log

### ISSUE THREAD

**Issue by SylvainGa** [claudegel/sinope-gt130#1]
Hi Claude,

Once upgraded to 109.1, I'm seeing this in my log and told to report to the dev, so here I am :-)

2020-04-30 22:58:29 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for neviweb130 doing I/O at custom_components/neviweb130/__init__.py, line 190: timeout=self._timeout)

**Comment by claudegel** [comment]
Thank you.

Will check when I'm back home tonight

Claude Gelinas

**Comment by claudegel** [comment]
OK for now it is just a warning at startup. Instead of doing direct i/o to update devices data from Neviweb now we need to send data update request to the event loop that will take care of all request in order. This is to prevent two or more request to be sent at the same time or stalled request that slowdown the process.
I'll update the code to be conform to the async entity update.

**Comment by SylvainGa** [comment]
Great! Thanks.

**Comment by claudegel** [comment]
OK I've fixed the neviweb and neviweb130 doing I/O in event loop.

**Comment by SylvainGa** [comment]
Thanks for the quick fix, it works :-)
